# Number of pod replicas
replicaCount: 5

# Container image configuration
image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

# Image pull secrets (not needed for public nginx image)
imagePullSecrets: []

# Name override for chart resources
nameOverride: ""
fullnameOverride: ""

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration (disabled for Minikube simplicity)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# ServiceAccount configuration
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Horizontal Pod Autoscaler (disabled for simplicity)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Resource limits and requests
resources: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity rules
affinity: {}
